<?php
                   include '../lib/koneksi.php';
        
                    $id = $_GET['sptahu']; // menangkap id
                    $tahun = $_GET['tahun'];// menangkap id
                    $sql = "SELECT *,DATE_FORMAT(suratdate,'%d %M %Y') as suratdate,DATE_FORMAT(bcf15tgl,'%d %M %Y') as bcf15tgl, DATE_FORMAT(bc11tgl,'%d %M %Y') as bc11tgl, DATE_FORMAT(bltgl,'%d %M %Y') as bltgl FROM bcf15, seksi, tp3, tpp WHERE bcf15.idtpp=tpp.idtpp and bcf15.idseksitp3=seksi.idseksi and bcf15.idtp3=tp3.idtp3 and suratno=$id and tahun=$tahun "; // memanggil data dengan id yang ditangkap tadi
                    $query = mysql_query($sql);
                    $bcf15 = mysql_fetch_array($query);


                    ?>
                        <form method="POST">
                            <table width="100%" border="0">
                                <tr>
                                    <td colspan="5" height="5"><?php include '../report/headersurat.html'; ?></td>

                                </tr>
                                <tr><td></td><td width="12%">Nomor</td><td width="1%">:</td><td width="50%">S-<?php echo $bcf15['suratno'] ?><?php echo $bcf15['kd_tp3'] ?><?php echo $bcf15['tahun'] ?></td><td align="right"><?php echo $bcf15['suratdate'] ?></td></tr>
                                <tr><td></td><td width="12%">Sifat</td><td width="1%">:</td><td width="50%">Segera</td><td align="right"></td></tr>
                                <tr><td></td><td width="12%" valign="top">Hal</td><td width="1%" valign="top">:</td><td width="50%" valign="top">Pemberitahuan Barang Yang Dinyatakan<br> Sebagai Barang Tidak Dikuasai</td><td align="right"></td></tr>
                                <tr><td></td><td height="4" colspan="5"></td></tr>
                                <tr><td></td><td height="4" colspan="5"></td></tr>
                                <tr><td></td><td colspan="5">Yth. Pimpinan <?php if ($bcf15['consignee']=="To Order") {echo $bcf15['notify']; } elseif ($bcf15['consignee']=="to order") {echo $bcf15['notify']; } elseif ($bcf15['consignee']=="toorder") {echo $bcf15['notify']; } elseif ($bcf15['consignee']=="ToOrder") {echo $bcf15['notify']; } else  {echo $bcf15['consignee'];};?></td></tr>
                                <tr><td></td><td colspan="5"><?php if ($bcf15['consignee']=="To Order") {echo $bcf15['notifyadrress']; } elseif ($bcf15['consignee']=="to order") {echo $bcf15['notifyadrress']; } elseif ($bcf15['consignee']=="toorder") {echo $bcf15['notifyadrress']; } elseif ($bcf15['consignee']=="ToOrder") {echo $bcf15['notifyadrress']; } else  {echo $bcf15['consigneeadrress'];};?><?php if ($bcf15['consignee']=="Notify Party") {echo $bcf15['notifyadrress']; } else  {echo $bcf15['consigneeadrress'];;};?></td></tr>
                                <tr><td></td><td colspan="5"><?php if ($bcf15['consignee']=="To Order") {echo $bcf15['notifykota']; } elseif ($bcf15['consignee']=="to order") {echo $bcf15['notifykota']; } elseif ($bcf15['consignee']=="toorder") {echo $bcf15['notifykota']; } elseif ($bcf15['consignee']=="ToOrder") {echo $bcf15['notifykota']; } else  {echo $bcf15['consigneekota'];};?></td></tr>
                                <tr><td></td><td height="5" colspan="4"></td></tr>
                                <tr><td colspan="5">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font >Diberitahukan dengan hormat bahwa berdasarkna Undang-Undang Nomor 10 Tahun 1995 tentang Kepabeanan sebagaimana diubah dengan Undang-Undang Nomor 17 Tahun 2006 dan Peraturan Menteri Keuangan nomor : 62/PMK.04/2011 tentang Penyelesaian Terhadap Barang Yang Dinyatakan Tidak Dikuasai, Barang Yang Dikuasai Negara dan Barang Yang Menjadi Milik Negara maka terhadap barang impor Suadara dengan data :</font></td></tr>
                                <tr><td height="5" colspan="6"></td></tr>
                                <tr><td colspan="3">BC 1.1</td><td colspan="2"  valign="middle" >: <?php echo $bcf15['bc11no'] ?> / Pos <?php echo $bcf15['bc11pos'] ?> Tanggal <?php echo $bcf15['bc11tgl'] ?></td></tr>
                                <tr><td colspan="3">Nama Kapal/Voy</td><td colspan="2"  valign="middle" >: <?php echo $bcf15['saranapengangkut'] ?> / <?php echo $bcf15['voy'] ?></td></tr>
                                <tr><td colspan="3">BCF 1.5 / Tgl</td><td colspan="2"  valign="middle" >: <?php echo $bcf15['bcf15no'] ?> / <?php echo $bcf15['bcf15tgl'] ?></td></tr>
                                <tr><td colspan="3">Lokasi Penimbunan</td><td colspan="2"  valign="middle" >: <?php echo $bcf15['nm_tpp'] ?> </td></tr>
                                <tr><td colspan="3">Kontainer</td><td colspan="2"  valign="middle" >: <?php $sql="SELECT max(idbcf15), nocontainer, idsize FROM bcfcontainer where idbcf15='$bcf15[idbcf15]'"; $data=mysql_query($sql); $tampil=mysql_fetch_array($data); echo $tampil['nocontainer']; ?>  <?php  $rowset = mysql_query("select  count(nocontainer) as nocontainer from bcfcontainer where idbcf15=$bcf15[idbcf15] and idsize='20'") ; $data2 = mysql_fetch_array($rowset); $jumlah = $data2['nocontainer']; if($jumlah>0) { echo "($jumlah x 20')";} else {echo '';}  $rowset1 = mysql_query("select  count(nocontainer) as nocontainer from bcfcontainer where idbcf15=$bcf15[idbcf15] and idsize='40'") ; $data3 = mysql_fetch_array($rowset1); $jumlah = $data3['nocontainer']; $cek1=mysql_numrows($rowset1);if($jumlah>0) { echo "($jumlah x 40')";} else  {echo '';} $rowset2 = mysql_query("select  count(nocontainer) as nocontainer from bcfcontainer where idbcf15=$bcf15[idbcf15] and idsize='45'") ; $data4 = mysql_fetch_array($rowset2); $jumlah = $data4['nocontainer']; $cek2=mysql_numrows($rowset2);if($jumlah>0) { echo "($jumlah x 45')";} else  {echo '';} ?> <?php $rowset = mysql_query("select * from bcf15,typecode where bcf15.idtypecode=typecode.idtypecode and idbcf15=$bcf15[idbcf15]"); while($typecode = mysql_fetch_array($rowset)){ if ($typecode['idtypecode']=="3") {echo $typecode['nm_type'];} elseif ($typecode['idtypecode']=="1") {echo $typecode['nm_type'];} elseif($typecode['idtypecode']=="4") {echo $typecode['nm_type'];} elseif($typecode['idtypecode']=="5") {echo $typecode['nm_type'];} elseif($typecode['idtypecode']=="6") {echo $typecode['nm_type'];} };?> </td></tr>
                                <tr><td colspan="3">Nomor B/L</td><td colspan="2"  valign="middle" >: <?php echo $bcf15['blno'] ?> / <?php echo $bcf15['bltgl'] ?> </td></tr>
                                <tr><td colspan="3">Jumlah / Jenis Barang</td><td colspan="2"  valign="middle" >: <?php echo $bcf15['amountbrg'] ?>  <?php echo $bcf15['satuanbrg'] ?>  <?php echo $bcf15['diskripsibrg'] ?> </td></tr>
                                <tr><td></td><td height="5" colspan="5"></td></tr>
                                <tr><td align="left" valign="top" width="10" >1.</td><td colspan="4" valign="top"><p style="text-align: justify">Berdasarkan pasal 65 Undang - Undang Nomor 10 Tahun 1995 tentang Kepabeanan sebagaimana diubah dengan Undang - Undang Nomor 17 Tahun 2006 dinyatakan sebagai Barang Yang Tidak Dikuasai, karena ditimbun di Tempat Penimbunan Sementara (TPS) yang melebihi jangka waktu 30 (tiga puluh) hari sejak tanggal penimbunan di TPS yang berada dalam area pelabuhan atau 60(enam puluh) hari sejak tanggal penimbunan di TPS yang berada diluar area pelabuhan.</p></td></tr>
                                <tr><td></td><td height="5" colspan="5"></td></tr>
                                <tr><td align="left" valign="top" >2.</td><td colspan="4" valign="top"><p style="text-align: justify">Dalam hal pemilik barang / kuasanya tidak menyelesaikan kewajiban pabeannya setelah jangka waktu 60 (enam puluh) hari sejak di simpan di Tempat Penimbunan Pabean atau tempat lain yang berfungsi sebagai Tempat Penimbunan Pabean berdasarkan pasal 4 ayat 2 Peraturan Menteri Keuangan tersebut diatas, Direktorat Jenderal Bea dan Cukai dapat melaksanakan pelelangan atas barang-barang dimaksud.</p></td></tr>
                                <tr><td></td><td height="5" colspan="5"></td></tr>
                                
                                <tr><td colspan="5">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font >Demikian pemberitahuan ini disampaikan untuk diketahui.</font></td></tr>
                                <tr><td></td><td height="10" colspan="5"></td></tr>
                                <tr><td colspan="5">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;an. Kepala Kantor </font></td></tr>
                                <tr><td colspan="5">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kabid Pelayanan Pabean dan Cukai II </font></td></tr>
                                <tr><td align="left" colspan="5">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;u.b. </font></td></tr>
                                <tr><td colspan="5">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $bcf15['jabatan'] ?> </font></td></tr>
                                <tr><td></td><td height="40" colspan="5"></td></tr>
                                <tr><td colspan="5">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $bcf15['nm_seksi'] ?> </font></td></tr>
                                <tr><td colspan="5">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NIP <?php echo $bcf15['nip'] ?> </font></td></tr>
                                <tr><td></td><td height="2" colspan="5"></td></tr>
                                <tr><td align="left" valign="top" colspan="5" ><p style="text-align: justify">Tembusan :</p></td></tr>
                               <tr><td align="left" valign="top" >1.&nbsp;&nbsp;&nbsp;</td><td colspan="4" valign="top"><p style="text-align: justify">Yth. Kepala Bidang PPC III;</p></td></tr>
                                <tr><td align="left" valign="top" >2.&nbsp;&nbsp;&nbsp;</td><td colspan="4" valign="top"><p style="text-align: justify">Pengusaha TPP <?php echo $bcf15['nm_tpp'] ?>;</p></td></tr>
                                <tr><td align="left" valign="top" >3.&nbsp;&nbsp;&nbsp;</td><td colspan="4" valign="top"><p style="text-align: justify">Pengusaha Pelayaran Not Define In Database</p></td></tr>
                            </table>
                        </form>